const Joi = require('joi');

const orderItemSchema = Joi.object({
  productId: Joi.string().allow('', null).optional(),
  name: Joi.string().trim().required(),
  price: Joi.number().min(0).required(),
  quantity: Joi.number().min(1).required(),
  foodType: Joi.string().allow('', null).default('veg'),
  note: Joi.string().trim().allow('', null).default(''),
});

const paymentDetailItemSchema = Joi.object({
  paymentType: Joi.string().allow('', null).default('CASH'),
  paymentName: Joi.string().allow('', null).default('CASH'),
  amount: Joi.number().min(0).required(),
  paymentMethod: Joi.string().allow('', null).default('CASH'),
  ncReason: Joi.string().allow('', null).default(''),
});

const generatePosOrderSchema = Joi.object({
  VenderUserId: Joi.string().allow('', null).optional(),
  venderUserId: Joi.string().allow('', null).optional(),
  vendorUserId: Joi.string().allow('', null).optional(),
  VenderCardId: Joi.string().allow('', null).optional(),
  venderCardId: Joi.string().allow('', null).optional(),
  CreatedByUserId: Joi.string().allow('', null).optional(),
  createdByUserId: Joi.string().allow('', null).optional(),
  CreatedByCardId: Joi.string().allow('', null).optional(),
  createdByCardId: Joi.string().allow('', null).optional(),
  cartId: Joi.string().allow('', null).optional(),
  cart: Joi.any().optional(),
  isKOT: Joi.boolean().optional().default(false),
  paymentDetails: Joi.array().items(paymentDetailItemSchema).optional().default([]),
  ncReason: Joi.string().allow('', null).default(''),
  paymentMode: Joi.string().allow('', null).default('CASH'),
  orderDevice: Joi.string().allow('', null).default('web'),
  isPaid: Joi.boolean().optional().default(false),
  isDineIn: Joi.boolean().optional().default(false),
  R: Joi.string().allow('', null).optional(),
  T: Joi.string().allow('', null).optional(),
  reason: Joi.string().allow('', null).default(''),
  remarks: Joi.string().allow('', null).default(''),
  clientSyncId: Joi.string().allow('', null).optional(),
  syncId: Joi.string().allow('', null).optional(),
  localOrderId: Joi.string().allow('', null).optional(),
  _id: Joi.string().allow('', null).optional(),
  orderNo: Joi.string().allow('', null).optional(),
  orderNO: Joi.string().allow('', null).optional(),
  orderNumber: Joi.string().allow('', null).optional(),
  TokenNo: Joi.string().allow('', null).optional(),
  tokenNo: Joi.string().allow('', null).optional(),
  orderId: Joi.string().allow('', null).optional(),
  idempotencyKey: Joi.string().allow('', null).optional(),
  items: Joi.array().items(orderItemSchema).optional(),
  subtotal: Joi.number().min(0).optional(),
  discountAmount: Joi.number().min(0).optional(),
  taxAmount: Joi.number().min(0).optional(),
  cgst: Joi.number().min(0).optional(),
  sgst: Joi.number().min(0).optional(),
  igst: Joi.number().min(0).optional(),
  tipAmount: Joi.number().min(0).optional(),
  totalAmount: Joi.number().min(0).optional(),
  paymentMethod: Joi.string().allow('', null).optional(),
  paymentStatus: Joi.string().allow('', null).optional(),
  customerName: Joi.string().allow('', null).optional(),
  customerPhone: Joi.string().allow('', null).optional(),
  tableNumber: Joi.string().allow('', null).optional(),
  orderType: Joi.string().allow('', null).optional(),
  status: Joi.string().valid('pending', 'preparing', 'ready', 'completed', 'cancelled', 'paid').optional(),
  notes: Joi.string().allow('', null).optional(),
});

const createOrderSchema = Joi.object({
  orderNumber: Joi.string().allow('', null).optional(),
  orderType: Joi.string().allow('', null).default('dineIn'),
  status: Joi.string().valid('pending', 'preparing', 'ready', 'completed', 'cancelled', 'paid').optional(),
  tableNumber: Joi.string().trim().allow('', null).default(''),
  customerName: Joi.string().trim().allow('', null).default(''),
  customerPhone: Joi.string().trim().allow('', null).default(''),
  items: Joi.array().items(orderItemSchema).min(1).optional(),
  cartId: Joi.string().allow('', null).optional(),
  subtotal: Joi.number().min(0).optional(),
  discountAmount: Joi.number().min(0).default(0),
  taxAmount: Joi.number().min(0).default(0),
  cgst: Joi.number().min(0).optional(),
  sgst: Joi.number().min(0).optional(),
  igst: Joi.number().min(0).optional(),
  tipAmount: Joi.number().min(0).default(0),
  totalAmount: Joi.number().min(0).optional(),
  paymentMethod: Joi.string().allow('', null).default('unpaid'),
  paymentStatus: Joi.string().allow('', null).default('pending'),
  kotStatus: Joi.string().allow('', null).default('not_sent'),
  kotNumber: Joi.number().allow(null).default(0),
  notes: Joi.string().trim().allow('', null).default(''),
  createdAt: Joi.any().optional(),
  idempotencyKey: Joi.string().allow('', null).optional(),
  clientSyncId: Joi.string().allow('', null).optional(),
  localOrderId: Joi.string().allow('', null).optional(),
  syncId: Joi.string().allow('', null).optional(),
  paymentDetails: Joi.array().items(paymentDetailItemSchema).optional(),
  paymentMode: Joi.string().allow('', null).optional(),
  orderDevice: Joi.string().allow('', null).optional(),
  isPaid: Joi.boolean().optional(),
  isDineIn: Joi.boolean().optional(),
  isKOT: Joi.boolean().optional(),
  ncReason: Joi.string().allow('', null).optional(),
  VenderUserId: Joi.string().allow('', null).optional(),
  venderUserId: Joi.string().allow('', null).optional(),
  VenderCardId: Joi.string().allow('', null).optional(),
  venderCardId: Joi.string().allow('', null).optional(),
  CreatedByUserId: Joi.string().allow('', null).optional(),
  createdByUserId: Joi.string().allow('', null).optional(),
  CreatedByCardId: Joi.string().allow('', null).optional(),
  createdByCardId: Joi.string().allow('', null).optional(),
  R: Joi.string().allow('', null).optional(),
  T: Joi.string().allow('', null).optional(),
  reason: Joi.string().allow('', null).optional(),
  remarks: Joi.string().allow('', null).optional(),
  orderNo: Joi.string().allow('', null).optional(),
  orderNO: Joi.string().allow('', null).optional(),
  TokenNo: Joi.string().allow('', null).optional(),
  tokenNo: Joi.string().allow('', null).optional(),
  orderId: Joi.string().allow('', null).optional(),
}).or('items', 'cartId').messages({
  'object.missing': 'Either items array or cartId must be provided',
});

const updateOrderStatusSchema = Joi.object({
  status: Joi.string().valid('pending', 'preparing', 'ready', 'completed', 'cancelled', 'paid').required(),
  reason: Joi.string().allow('', null).optional(),
});

const payOrderSchema = Joi.object({
  paymentMethod: Joi.string().allow('', null).default('cash'),
  amountPaid: Joi.number().min(0).optional(),
});

module.exports = {
  createOrderSchema,
  generatePosOrderSchema,
  updateOrderStatusSchema,
  payOrderSchema,
};
